const jeux = [
    // PS4 
    { nom: "Ace Combat 7 Skies Unknown", genre: ["Action", "Simulation"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/154643/1546433419-2302-jaquette-avant.jpg" },
    { nom: "Anthem", genre: ["Action", "Rpg"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/152899/1528988869-4237-jaquette-avant.jpg" },
    { nom: "Aragami", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/146124/1461242484-124-jaquette-avant.png" },
    { nom: "Assassin'S Creed Syndicate", genre: ["Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/151256/1512556145-5805-jaquette-avant.jpg" },
    { nom: "Assassin'S Creed Unity", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00048287/jaquette-assassin-s-creed-unity-pc-cover-avant-g-1407851395.jpg" },
    { nom: "Assassin'S Creed Odyssey", genre: ["Aventure", "Rpg"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/152876/1528757449-2875-jaquette-avant.png" },
    { nom: "Assassin'S Creed Origins", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/149760/1497601876-9386-jaquette-avant.jpg" },
    { nom: "Astro Bot Rescue Mission", genre: ["Action"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/152715/1527154114-5484-jaquette-avant.jpg" },
    { nom: "Batman Arkham Knight", genre: ["Aventure", "Action"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00051937/jaquette-batman-arkham-knight-pc-cover-avant-g-1393950022.jpg" },
    { nom: "Battlefield 1", genre: ["Fps"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/146797/1467969692-7420-jaquette-avant.jpg" },
    { nom: "Battlefield V", genre: ["Fps"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/152899/1528988126-8607-jaquette-avant.jpg" },
    { nom: "Blood Bowl Ii", genre: ["Stratégie", "Sport"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/148665/1486650241-3307-jaquette-avant.jpg" },
    { nom: "Borderlands 3", genre: ["Fps"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Coop Local"], image: "https://image.jeuxvideo.com/medias-sm/155724/1557239235-3469-jaquette-avant.jpg" },
    { nom: "Call Of Duty Black Ops Iii", genre: ["Fps", "Action"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local", "Coop En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/153010/1530101536-2688-jaquette-avant.jpg" },
    { nom: "Call Of Duty Black Ops Iiii", genre: ["Fps", "Action"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local", "Coop En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/152899/1528989036-4103-jaquette-avant.jpg" },
    { nom: "Call Of Duty Modern Warfare", genre: ["Fps", "Action"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local", "Coop En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/156500/1564996408-5796-jaquette-avant.jpeg" },
    { nom: "Control", genre: ["Tps", "Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/159975/1599745259-6450-jaquette-avant.png" },
    { nom: "Crash Bandicoot N Sane Trilogy", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/152758/1527579576-5515-jaquette-avant.jpg" },
    { nom: "Crash Team Racing Nitro Fueld", genre: ["Course", "Arcade"], console: ["Ps4"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/149579/1495790807-8533-jaquette-avant.jpg" },
    { nom: "Darksiders Iii", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/154238/1542377094-3974-jaquette-avant.png" },
    { nom: "Days Gone", genre: ["Action", "Aventure", "Survival"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/162134/1621344690-8243-jaquette-avant.jpg" },
    { nom: "Dead Cells", genre: ["Action", "Roguelike"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/148493/1484926001-3121-jaquette-avant.jpg" },
    { nom: "Dead Or Alive 5 Last Round", genre: ["Combat", "Action"], console: ["Ps4"], mode: ["Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/142315/1423154673-7746-jaquette-avant.jpg" },
    { nom: "Death Stranding", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/170612/1706120640-3885-jaquette-avant.jpg" },
    { nom: "Deponia", genre: ["Aventure", "Point And Click"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00041937/jaquette-deponia-pc-cover-avant-g-1340286561.jpg" },
    { nom: "Destiny Le Roi Des Corrompus", genre: ["Fps", "Action", "Rpg"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/143453/1434530894-4650-jaquette-avant.jpg" },
    { nom: "Deus Ex Mankind Divided", genre: ["Action", "Rpg", "Infiltration"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/142962/1429622143-8749-jaquette-avant.jpg" },
    { nom: "Devil May Cry 5", genre: ["Action"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/154885/1548853332-2097-jaquette-avant.jpg" },
    { nom: "Disco Elysium", genre: ["Rpg", "Aventure Narrative"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/163247/1632474947-6395-jaquette-avant.jpg" },
    { nom: "Dragon Ball Fighter Z", genre: ["Combat", "Action"], console: ["Ps4"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/151681/1516808715-4062-jaquette-avant.jpg" },
    { nom: "Dragonball Xenoverse 2", genre: ["Combat", "Action", "Rpg"], console: ["Ps4"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://m.media-amazon.com/images/I/71mJMs8Ra7L._AC_UF1000,1000_QL80_.jpg" },
    { nom: "Driveclub", genre: ["Course", "Sport"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00047923/jaquette-drive-club-playstation-4-ps4-cover-avant-g-1370964123.jpg" },
    { nom: "Dying Light", genre: ["Action", "Survival"], console: ["Ps4"], mode: ["Solo", "Coop En Ligne"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00048805/jaquette-dying-light-pc-cover-avant-g-1369671143.jpg" },
    { nom: "Everybody'S Golf Vr", genre: ["Sport"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/155378/1553781439-7471-jaquette-avant.jpg" },
    { nom: "Fallout 4", genre: ["Rpg", "Action"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/143533/1435331352-4036-jaquette-avant.jpg" },
    { nom: "Far Cry 4", genre: ["Action", "Fps", "Aventure"], console: ["Ps4"], mode: ["Solo", "Coop En Ligne"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00047842/jaquette-far-cry-4-pc-cover-avant-g-1416214114.jpg" },
    { nom: "Far Cry Primal", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/151921/1519207647-8340-jaquette-avant.jpg" },{ nom: "Fifa 19", genre: ["Sport"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/152856/1528561887-2268-jaquette-avant.jpg" },
    { nom: "Fifa 20", genre: ["Sport"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/156043/1560428142-7284-jaquette-avant.jpg" },
    { nom: "Final Fantasy Vii Remake", genre: ["Action", "Rpg"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/165271/1652708142-5232-jaquette-avant.jpg" },
    { nom: "Game Of Thrones", genre: ["Aventure Narrative"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/148285/1482846917-3112-jaquette-avant.jpg" },
    { nom: "Ghost Recon Wildlands", genre: ["Action"], console: ["Ps4"], mode: ["Solo", "Coop En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/150530/1505304776-1939-jaquette-avant.jpg" },
    { nom: "God Of War", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/164200/1642003637-1975-jaquette-avant.jpg" },
    { nom: "Gravity Rush 2", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/147377/1473773124-3458-jaquette-avant.jpg" },
    { nom: "Gt Sport", genre: ["Course", "Sport"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/150530/1505296408-6011-jaquette-avant.jpg" },
    { nom: "Gta V", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/163129/1631287693-8700-jaquette-avant.jpg" },
    { nom: "Hitman", genre: ["Action", "Infiltration"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/148164/1481635156-7245-jaquette-avant.jpg" },
    { nom: "Horizon Zero Dawn", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://m.media-amazon.com/images/I/81vvVJzwSIL.jpg" },
    { nom: "Infamous Second Son", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/151819/1518189971-6305-jaquette-avant.jpg" },
    { nom: "Injustice 2", genre: ["Combat"], console: ["Ps4"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/151983/1519828047-7784-jaquette-avant.png" },
    { nom: "It Takes Two", genre: ["Aventure", "Plateforme"], console: ["Ps4", "Switch"], mode: ["Coop Local", "Coop En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/161588/1615882370-8461-jaquette-avant.jpg" },
    { nom: "Killzone Shadow Fall", genre: ["Fps", "Action"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00042897/jaquette-killzone-shadow-fall-playstation-4-ps4-cover-avant-g-1391027988.jpg" },
    { nom: "Kingdom Hearts 1.5 + 2.5", genre: ["Action", "Rpg"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/164396/1643964057-6392-jaquette-avant.jpg" },
    { nom: "Knack", genre: ["Action", "Plateforme"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00047922/jaquette-knack-playstation-4-ps4-cover-avant-g-1388412429.jpg" },
    { nom: "Knack Ii", genre: ["Action", "Plateforme"], console: ["Ps4"], mode: ["Solo", "Coop Local"], image: "https://image.jeuxvideo.com/medias-sm/149908/1499075653-9236-jaquette-avant.jpg" },
    { nom: "Lego Batman3 Au Dela De Gotham", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo", "Coop Local"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00052846/jaquette-lego-batman-3-au-dela-de-gotham-pc-cover-avant-g-1415869733.jpg" },
    { nom: "Lego Marvel Super Heroes", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo", "Coop Local"], image: "https://image.jeuxvideo.com/medias-sm/148294/1482940516-3931-jaquette-avant.jpg" },
    { nom: "Life Is Strange", genre: ["Aventure Narrative"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/154565/1545645728-2233-jaquette-avant.jpg" },
    { nom: "Little Big Planet 3", genre: ["Plateforme"], console: ["Ps4"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne", "Coop Local"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00047832/jaquette-littlebigplanet-3-playstation-4-ps4-cover-avant-g-1413447709.jpg" },
    { nom: "Mass Effect Andromeda", genre: ["Action", "Rpg", "Science-Fiction"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/148977/1489768892-4900-jaquette-avant.jpg" },
    { nom: "Metro Exodus", genre: ["Fps", "Action", "Survie"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/149723/1497234393-5453-jaquette-avant.jpg" },
    { nom: "Monster Hunter World", genre: ["Action", "Rpg"], console: ["Ps4"], mode: ["Solo", "Coop En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/149760/1497601320-218-jaquette-avant.jpg" },
    { nom: "Moss", genre: ["Aventure", "Vr"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/167048/1670482724-1597-jaquette-avant.jpg" },
    { nom: "Mortal Combat Xl", genre: ["Combat"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/154867/1548672895-1227-jaquette-avant.jpg" },
    { nom: "Motogp 15", genre: ["Course", "Sport"], console: ["Ps4"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT5aiKvJ5LsqbhCxoaKd95wlSWEpyHB0384Q&s" },
    { nom: "Need For Speed", genre: ["Course", "Action"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/143447/1434465010-8714-jaquette-avant.jpg" },
    { nom: "Nero", genre: ["Aventure Narrative"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/150514/1505141731-4438-jaquette-avant.jpg" },
    { nom: "Nier : Automata", genre: ["Action", "Rpg"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/150530/1505304310-2020-jaquette-avant.jpg" },
    { nom: "Okami", genre: ["Action", "Aventure"], console: ["Ps4", "Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/150754/1507539164-1511-jaquette-avant.jpg" },
    { nom: "Payday 2", genre: ["Action", "Fps"], console: ["Ps4"], mode: ["Coop En Ligne"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00045331/jaquette-payday-2-pc-cover-avant-g-1363120040.jpg" },
    { nom: "Pes 2016 Pro Evolution Soccer", genre: ["Sport"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/143412/1434119855-9571-jaquette-avant.jpg" },
    { nom: "Prey", genre: ["Action", "Aventure", "Fps", "Science-Fiction"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/146579/1465791090-4094-jaquette-avant.jpg" },
    { nom: "Ratchet & Clank", genre: ["Action", "Aventure", "Plateforme"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/145641/1456413066-1332-jaquette-avant.jpg" },
    { nom: "Rainbow Six Siege", genre: ["Fps"], console: ["Ps4"], mode: ["Multijoueur En Ligne", "Coop En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/151681/1516808294-7261-jaquette-avant.jpg" },
    { nom: "Red Dead Redemption Ii", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/165165/1651652506-3619-jaquette-avant.jpg" },
    { nom: "Resident Evil 2", genre: ["Horreur", "Action"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/154643/1546433679-8438-jaquette-avant.jpg" },
    { nom: "Resident Evil Vii", genre: ["Horreur", "Fps"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/147143/1471433021-1572-jaquette-avant.jpg" },
    { nom: "Saint Seiya Soldiers' Soul", genre: ["Combat", "Action"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/142891/1428909837-3298-jaquette-avant.jpg" },
    { nom: "Sekiro Shadows Die Twice", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/152905/1529054204-3792-jaquette-avant.jpg" },
    { nom: "Shadow Of The Colossus", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/151670/1516698328-1441-jaquette-avant.jpg" },
    { nom: "Sniper Elite Iii", genre: ["Tps"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Coop En Ligne"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00048124/jaquette-sniper-elite-iii-pc-cover-avant-g-1405409689.jpg" },
    { nom: "Soulcalibur Vi", genre: ["Combat"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/153062/1530619111-5868-jaquette-avant.jpg" },
    { nom: "Spiderman", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/165979/1659788590-4351-jaquette-avant.jpg" },
    { nom: "Spyro Reignited Trilogy", genre: ["Plateforme", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/156050/1560502971-6125-jaquette-avant.jpg" },
    { nom: "Star Wars Battlefront Ii", genre: ["Tps"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Coop En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/150530/1505296141-1595-jaquette-avant.jpg" },
    { nom: "Star Wars Fallen Order", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/163155/1631548086-1467-jaquette-avant.jpg" },
    { nom: "Street Fighter V", genre: ["Combat"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/146736/1467358229-4937-jaquette-avant.jpg" },
    { nom: "Subnautica", genre: ["Aventure", "Survival"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/151681/1516807923-9666-jaquette-avant.jpg" },
    { nom: "Tales Of Zestiria", genre: ["Rpg", "Action"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/151249/1512492514-7512-jaquette-avant.jpg" },
    { nom: "Team Sonic Racing", genre: ["Course"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/154886/1548859627-785-jaquette-avant.jpg" },
    { nom: "Tekken 7", genre: ["Combat"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/150531/1505305015-2552-jaquette-avant.jpg" },
    { nom: "The Last Guardian", genre: ["Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/148059/1480589767-5568-jaquette-avant.jpg" },
    { nom: "The Last Of Us Part Ii", genre: ["Action", "Survival"], console: ["Ps4"], mode: ["Solo"], image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVNyx7Mh4jFVBII0qJ7dPBFxtDm2yJPaPX5w&s" },
    { nom: "The Last Of Us Remastered", genre: ["Action", "Survival"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00052332/jaquette-the-last-of-us-remastered-playstation-4-ps4-cover-avant-g-1397063678.jpg" },
    { nom: "The Order 1886", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/142472/1424715962-4092-jaquette-avant.jpg" },
    { nom: "The Outer Worlds", genre: ["Rpg"], console: ["Ps4"], mode: ["Solo"], image: "https://m.media-amazon.com/images/I/71mmbRHySNL._AC_UF1000,1000_QL80_.jpg" },
    { nom: "Thief", genre: ["Aventure", "Infiltration"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00031191/jaquette-thief-pc-cover-avant-g-1376946696.jpg" },
    { nom: "Titanfall 2", genre: ["Fps"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/146581/1465811390-1442-jaquette-avant.jpg" },
    { nom: "Tony Hawk'S Pro Skater 5", genre: ["Sport"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/143454/1434543134-9214-jaquette-avant.jpg" },
    { nom: "Ufc", genre: ["Sport", "Combat"], console: ["Ps4"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://static.fnac-static.com/multimedia/Images/2C/12/0B/12/18919724-1505-3756-1/tsp20221201073058/EA-Sports-UFC-PS4.jpg" },
    { nom: "Uncharted - The Natan Drake Collection", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://m.media-amazon.com/images/I/81i4ORYqGpL.jpg" },
    { nom: "Uncharted 4", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://m.media-amazon.com/images/I/71ODUH6DxIL._AC_UF1000,1000_QL80_.jpg" },
    { nom: "Untildawn", genre: ["Horreur", "Aventure Narrative"], console: ["Ps4"], mode: ["Solo"], image: "https://m.media-amazon.com/images/I/71u2tCNG5QL.jpg" },
    { nom: "Valkyria Chronicles Remastered", genre: ["Rpg", "Tps", "Aventure", "Stratégie"], console: ["Ps4"], mode: ["Solo"], image: "https://m.media-amazon.com/images/I/71+hF0s6xcL._AC_UF1000,1000_QL80_.jpg" },
    { nom: "W2K15", genre: ["Sport", "Combat"], console: ["Ps4"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://static.fnac-static.com/multimedia/Images/FR/NR/9b/89/5c/6064539/1507-1/tsp20250116215547/WWE-2K15-PS4.jpg" },
    { nom: "Watch Dogs 2", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://m.media-amazon.com/images/I/91NDo4e+WfL.jpg" },
    { nom: "Watch Dogs", genre: ["Action", "Aventure"], console: ["Ps4"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPk5E4dJNinrLd6NRIJNhfwjL1qoaAd8nt8g&s" },
    { nom: "Wolfenstein 2", genre: ["Fps", "Action"], console: ["Ps4"], mode: ["Solo"], image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpDYfB-llkUnvvxRCW5qLiWBYGuks3kkLxrA&s" },
    { nom: "Worms Battlegrounds", genre: ["Stratégie"], console: ["Ps4"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/142850/1428496622-4427-jaquette-avant.jpg" },{ nom: "Wrc", genre: ["Course", "Sport"], console: ["Ps4"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://m.media-amazon.com/images/I/71iZFjTkw3L.jpg" },
    { nom: "Yooka-Laylee", genre: ["Plateforme", "Aventure"], console: ["Ps4"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/143825/1438249689-9502-jaquette-avant.jpg" },

    // PS5
    { nom: "2K25", genre: ["Sport"], console: ["Ps5"], mode: ["Solo", "Multijoueur "], image: "https://image.jeuxvideo.com/medias-sm/172070/1720700902-1325-jaquette-avant.png" },
    { nom: "A Plague Tale Innocence", genre: ["Aventure", "Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/155180/1551804874-6122-jaquette-avant.jpg" },
    { nom: "A Plague Tale Requiem", genre: ["Aventure"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/164061/1640614108-8759-jaquette-avant.gif" },
    { nom: "Armored Core 6 Fires Of Rubicon", genre: ["Aventure", "Action"], console: ["Ps5"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/169340/1693398307-960-jaquette-avant.jpg" },
    { nom: "Assassin'S Creed Mirage", genre: ["Aventure", "Action"], console: ["Ps5"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/169574/1695736870-1912-jaquette-avant.jpg" },
    { nom: "Assassin'S Creed Shadows", genre: ["Action", "Rpg"], console: ["Ps5"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/171579/1715789028-8027-jaquette-avant.png" },
    { nom: "Assassin'S Creed Valhalla", genre: ["Action", "Rpg"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/158826/1588264397-5261-jaquette-avant.jpg" },
    { nom: "Astro Bot", genre: ["Action"], console: ["Ps5"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/171714/1717140412-8272-jaquette-avant.jpeg" },
    { nom: "Atomic Heart", genre: ["Action", "Rpg"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/167568/1675679804-810-jaquette-avant.png" },
    { nom: "Avatar Frontiers Of Pandora", genre: ["Action", "Aventure"], console: ["Ps5"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/163154/1631541841-4335-jaquette-avant.jpg" },
    { nom: "Banishers: Ghosts Of New Eden", genre: ["Aventure"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/169571/1695713394-6063-jaquette-avant.jpg" },
    { nom: "Blasphemous 2", genre: ["Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/168806/1688055929-1245-jaquette-avant.jpg" },
    { nom: "Call Of Duty - Black Ops 6", genre: ["Action", "Fps"], console: ["Ps5"], mode: ["Solo", "Multijoueur "], image: "https://image.jeuxvideo.com/medias-sm/172018/1720184406-1734-jaquette-avant.jpg" },
    { nom: "Call Of Duty : Vanguard", genre: ["Action", "Fps"], console: ["Ps5"], mode: ["Solo", "Multijoueur "], image: "https://image.jeuxvideo.com/medias-sm/163299/1632989599-6459-jaquette-avant.gif" },
    { nom: "Call Of Duty Modern Warfare 3", genre: ["Action", "Fps"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/169686/1696864254-5173-jaquette-avant.jpg" },
    { nom: "Crash Bandicoot It'S About Time", genre: ["Plateforme"], console: ["Ps5"], mode: ["Solo", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/161289/1612888573-6895-jaquette-avant.jpg" },
    { nom: "Dead Space Remastered", genre: ["Horreur"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/166513/1665131806-7452-jaquette-avant.jpg" },
    { nom: "Demon'S Souls", genre: ["Action"], console: ["Ps5"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/160033/1600327524-721-jaquette-avant.jpg" },
    { nom: "Diablo 4", genre: ["Action", "Rpg"], console: ["Ps5"], mode: ["Solo", "Multijoueur En Ligne", "Co-Op Local"], image: "https://image.jeuxvideo.com/medias-sm/165511/1655108114-4402-jaquette-avant.jpg" },
    { nom: "Dragon Age The Veilguard", genre: ["Action", "Rpg"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/172492/1724920403-3901-jaquette-avant.jpg" },
    { nom: "Dragon Ball - Sparking! Zero", genre: ["Combat"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/172018/1720184311-2338-jaquette-avant.jpg" },
    { nom: "Dragon'S Dogma 2", genre: ["Action", "Rpg"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/170119/1701185913-6681-jaquette-avant.jpg" },
    { nom: "Dying Light 2", genre: ["Action", "Horreur"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/163247/1632473272-6800-jaquette-avant.jpg" },
    { nom: "Elden Ring", genre: ["Action", "Rpg"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/163301/1633006670-7022-jaquette-avant.jpg" },
    { nom: "Fc 24", genre: ["Sport"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/168927/1689274370-118-jaquette-avant.jpeg" },
    { nom: "Fc 25", genre: ["Sport"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/172492/1724920373-1097-jaquette-avant.jpg" },
    { nom: "F1 22", genre: ["Sport", "Course"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/165159/1651593166-5861-jaquette-avant.jpg" },
    { nom: "F1 24", genre: ["Sport", "Course"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/171647/1716470975-4371-jaquette-avant.jpeg" },
    { nom: "Fifa 23", genre: ["Sport"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/165945/1659449057-7682-jaquette-avant.jpg" },
    { nom: "Final Fantasy Xvi", genre: ["Action", "Rpg"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/169380/1693804854-6462-jaquette-avant.jpg" },
    { nom: "Forspoken", genre: ["Action", "Rpg"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/166922/1669220301-2629-jaquette-avant.jpg" },
    { nom: "Ghost Of Tsushima", genre: ["Action", "Rpg"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/171018/1710175367-5672-jaquette-avant.jpg" },
    { nom: "Ghostrunner 2", genre: ["Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/169332/1693319950-4930-jaquette-avant.jpg" },
    { nom: "God Of War Ragnarok", genre: ["Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/171711/1717109795-2790-jaquette-avant.jpg" },
    { nom: "Goldorak - Le Festin Des Loups", genre: ["Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/167714/1677144306-1983-jaquette-avant.jpg" },
    { nom: "Gotham Knights", genre: ["Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/163395/1633953563-5828-jaquette-avant.jpg" },
    { nom: "Gran Turismo 7", genre: ["Course"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/163129/1631286486-2749-jaquette-avant.jpg" },
    { nom: "Helldivers 2", genre: ["Action"], console: ["Ps5"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/170661/1706612979-7633-jaquette-avant.jpg" },
    { nom: "Hitman World Of Assassination", genre: ["Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/148164/1481635156-7245-jaquette-avant.jpg" },
    { nom: "Hogwarts Legacy", genre: ["Action", "Rpg"], console: ["Ps5", "Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/163636/1636363677-7536-jaquette-avant.gif" },
    { nom: "Horizon - Forbidden West", genre: ["Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/163293/1632927582-7714-jaquette-avant.gif" },
    { nom: "Immortals Of Aveum", genre: ["Fps"], console: ["Ps5"], mode: ["Solo"], image: "https://m.media-amazon.com/images/I/81aSNF0+Q1L.jpg" },
    { nom: "Jedi Survivor", genre: ["Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/167526/1675258819-5809-jaquette-avant.png" },
    { nom: "Kena Bridge Of Spirits", genre: ["Action", "Aventure"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/163214/1632142889-7692-jaquette-avant.jpg" },
    { nom: "Lies Of P", genre: ["Action", "Rpg"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/163654/1636538174-709-jaquette-avant.gif" },
    { nom: "Lord Of The Fallen", genre: ["Action", "Rpg"], console: ["Ps5"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/169711/1697113662-3404-jaquette-avant.jpg" },
    { nom: "Midnight Suns", genre: ["Stratégie"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/163300/1633001932-5798-jaquette-avant.gif" },
    { nom: "Monster Hunter Wilds", genre: ["Action"], console: ["Ps5"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/172724/1727243544-8566-jaquette-avant.jpg" },
    { nom: "Mortal Kombat 1", genre: ["Combat"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/169332/1693318198-4280-jaquette-avant.jpg" },
    { nom: "Motogp 24", genre: ["Sport", "Course"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://m.media-amazon.com/images/I/813nW-rLBHL._AC_UL480_QL65_.jpg" },
    { nom: "Overcooked All You Can Eat", genre: ["Famille", "Simulation"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/170429/1704293465-3447-jaquette-avant.jpg" },
    { nom: "Playstation 5", genre: [""], console: ["Ps5"], mode: [""], image: "" },
    { nom: "Playstation 5 N°2", genre: [""], console: ["Ps5"], mode: [""], image: "" },
    { nom: "Prince Of Persia The Lost Crown", genre: ["Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/169814/1698141365-715-jaquette-avant.jpg" },
    { nom: "Ratchet & Clank : Rift Apart", genre: ["Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/171595/1715948278-914-jaquette-avant.jpg" },
    { nom: "Remnant", genre: ["Action", "Aventure"], console: ["Ps5"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://m.media-amazon.com/images/I/81TyAxKM7VL._AC_UL480_QL65_.jpg" },
    { nom: "Resident Evil 4 Remaster", genre: ["Horreur", "Aventure"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/167871/1678711307-842-jaquette-avant.jpg" },
    { nom: "Resident Evil Village", genre: ["Horreur", "Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/161979/1619789555-8363-jaquette-avant.jpg" },
    { nom: "Returnal", genre: ["Tps", "Roguelike"], console: ["Ps5"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/167412/1674116899-8623-jaquette-avant.jpg" },
    { nom: "Sniper Elite Resistance", genre: ["Tps"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/173385/1733848826-2681-jaquette-avant.jpg" },
    { nom: "Spider Man 2", genre: ["Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/173555/1735550271-2862-jaquette-avant.png" },
    { nom: "Spider-Man : Miles Morales", genre: ["Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/166395/1663949878-4886-jaquette-avant.jpg" },
    { nom: "Split Fiction", genre: ["Aventure"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/173436/1734363679-6812-jaquette-avant.png" },
    { nom: "Stellar Blade", genre: ["Aventure", "Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/170678/1706777513-3043-jaquette-avant.jpeg" },
    { nom: "Stray", genre: ["Aventure"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/172019/1720185348-8038-jaquette-avant.jpg" },
    { nom: "Suicide Squad", genre: ["Tps"], console: ["Ps5"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/164061/1640613097-8015-jaquette-avant.gif" },
    { nom: "Tekken 8", genre: ["Action", "Combat"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/169773/1697730820-2614-jaquette-avant.jpg" },
    { nom: "The Callisto Protocol", genre: ["Horreur"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/165945/1659449360-5058-jaquette-avant.jpeg" },
    { nom: "The Last Of Us Part I Remastered", genre: ["Action"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/165943/1659428750-8481-jaquette-avant.jpg" },
    { nom: "Tiny Tina'S Wonderlands", genre: ["Action", "Fps"], console: ["Ps5"], mode: ["Solo", "Multijoueur"], image: "https://image.jeuxvideo.com/medias-sm/163129/1631287409-8704-jaquette-avant.jpg" },
    { nom: "Uncharted Legacy Of Thieves Collection", genre: ["Action", "Aventure"], console: ["Ps5"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/163653/1636534544-5632-jaquette-avant.gif" },
    { nom: "Wo Long Fallen Dynasty", genre: ["Aventure", "Rpg"], console: ["Ps5"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/169963/1699634038-2227-jaquette-avant.jpg" },

    // Switch
    { nom: "1 2 Switch", genre: ["Party"], console: ["Switch"], mode: ["Multijoueur Local"], image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-95hVMXvHrKYmSLKc6F4dNqaNQQkgXpwLzuDrptiX4WCPR8DdPs65T_3lIws&s" },
    { nom: "Advance Wars 1&2 Re-Boot Camp", genre: ["Stratégie"], console: ["Switch"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/163342/1633421604-2955-jaquette-avant.gif" },
    { nom: "Arms", genre: ["Combat"], console: ["Switch"], mode: ["Solo", "Multijoueur En Ligne", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/148429/1484293005-1608-jaquette-avant.png" },
    { nom: "Astral Chain", genre: ["Action", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/159126/1591263956-8447-jaquette-avant.jpg" },
    { nom: "Bayonetta 1&2", genre: ["Action", "Hack & Slash"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/151972/1519719563-4588-jaquette-avant.jpg" },
    { nom: "Bayonetta 3", genre: ["Action", "Hack & Slash"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/166671/1666707428-6189-jaquette-avant.jpg" },
    { nom: "Biomutant", genre: ["Rpg", "Action", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/150530/1505296921-2396-jaquette-avant.jpg" },
    { nom: "Bravely Default 2", genre: ["Rpg"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/163000/1630000577-8743-jaquette-avant.jpg" },
    { nom: "Cadence Of Hyrule", genre: ["Action"], console: ["Switch"], mode: ["Solo", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/165183/1651829590-356-jaquette-avant.jpg" },
    { nom: "Cereza And The Lost Demon", genre: ["Action", "Rpg"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/167057/1670569159-5679-jaquette-avant.jpg" },
    { nom: "Crash Bandicoot N'Sane Trilogy", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/152758/1527579576-5515-jaquette-avant.jpg" },
    { nom: "Cult Of The Lamb", genre: ["Action", "Rogue-Like"], console: ["Switch"], mode: ["Solo", "Coop Local"], image: "https://image.jeuxvideo.com/medias-sm/166134/1661338737-306-jaquette-avant.jpg" },
    { nom: "Cuphead", genre: ["Action", "Plateforme", "Run & Gun"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/149751/1497514958-4620-jaquette-avant.png" },
    { nom: "Darkest Dungeon", genre: ["Rpg", "Stratégie", "Rogue-Like"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/151903/1519031927-7079-jaquette-avant.jpg" },
    { nom: "Darkest Dungeon", genre: [""], console: ["Switch"], mode: [""], image: "" },
    { nom: "Donkey Kong Country Returns", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo", "Coop Local"], image: "https://image.jeuxvideo.com/medias-sm/172009/1720086608-7673-jaquette-avant.jpg" },
    { nom: "Dragon Quest Builders", genre: ["Rpg", "Construction", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/170671/1706711699-2596-jaquette-avant.jpg" },
    { nom: "Fifa 24", genre: ["Sport", "Simulation"], console: ["Switch"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/168927/1689274370-118-jaquette-avant.jpeg" },
    { nom: "Fire Emblem Three Houses", genre: ["Rpg", "Stratégie", "Tactique"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/157132/1571322153-4340-jaquette-avant.jpg" },
    { nom: "Fire Emblem Warriors", genre: ["Action", "Stratégie", "Hack & Slash"], console: ["Switch"], mode: ["Solo", "Coop Local"], image: "https://image.jeuxvideo.com/medias-sm/150530/1505296979-469-jaquette-avant.jpg" },
    { nom: "Gris", genre: ["Aventure Narrative", "Plateforme"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/153417/1534169430-4644-jaquette-avant.jpg" },
    { nom: "Guilty Gear Strive", genre: ["Combat"], console: ["Switch"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/162159/1621590503-5214-jaquette-avant.png" },
    { nom: "Hades", genre: ["Action", "Rogue-Like", "Rpg"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/161367/1613665411-7537-jaquette-avant.png" },
    { nom: "Hogwarts Legacy Switch", genre: ["Rpg", "Action", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "" },
    { nom: "Hollow Knight", genre: ["Action", "Aventure", "Plateforme", "Metroidvania"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/152000/1519996933-2079-jaquette-avant.jpg" },
    { nom: "Hotline Miami Collection", genre: ["Action", "Fps"], console: ["Switch"], mode: ["Solo"], image: "https://m.media-amazon.com/images/I/519Q7WEoTDS._AC_UF1000,1000_QL80_.jpg" },
    { nom: "Just Dance 2019", genre: ["Sport", "Rythme"], console: ["Switch"], mode: ["Solo", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/152876/1528758245-3305-jaquette-avant.png" },
    { nom: "Just Dance 2024 Edition", genre: ["Sport", "Rythme"], console: ["Switch"], mode: ["Solo", "Multijoueur Local"], image: "https://m.media-amazon.com/images/I/71VKHJEoBFL._AC_UF1000,1000_QL80_.jpg" },
    { nom: "Kirby Et Le Monde Oublie", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/174361/1743608576-8972-jaquette-avant.jpg" },
    { nom: "Kirby'S  Return To Dream Land Deluxe", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo", "Coop Local"], image: "https://image.jeuxvideo.com/medias-sm/166314/1663143709-3753-jaquette-avant.jpg" },
    { nom: "L'Age De Glace La Folle Aventure De Scrat", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/156157/1561566051-2720-jaquette-avant.jpg" },
    { nom: "Legendes Pokemon : Arceus", genre: ["Rpg", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/163353/1633531106-3464-jaquette-avant.gif" },
    { nom: "Lego City Undercover", genre: ["Action", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCRdI3pNwjlyXHboorv5sa2NgIoJZwLVpHvP1hIlz3patXBfNdPzC1XygpQ&s" },
    { nom: "Lego Horizon Adventures", genre: ["Action", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/172724/1727243257-7510-jaquette-avant.jpg" },
    { nom: "Luigi'S Mansion 2", genre: ["Action", "Aventure", "Horreur Léger"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/170315/1703150862-6572-jaquette-avant.jpeg" },
    { nom: "Luigi'S Mansion 3", genre: ["Action", "Aventure", "Horreur Léger"], console: ["Switch"], mode: ["Solo", "Coop Local"], image: "https://image.jeuxvideo.com/medias-sm/157225/1572254593-9025-jaquette-avant.jpg" },
    { nom: "Mario & Luigi - L'Epopee Fraternelle", genre: ["Rpg", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/172009/1720085360-2848-jaquette-avant.jpg" },
    { nom: "Mario Strikers", genre: ["Sport", "Action"], console: ["Switch"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/164457/1644568163-7646-jaquette-avant.png" },
    { nom: "Mario Tennis Aces", genre: ["Sport", "Action"], console: ["Switch"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/152899/1528989719-8835-jaquette-avant.jpg" },
    { nom: "Mariokart 8 Deluxe", genre: ["Course"], console: ["Switch"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/149391/1493907906-4936-jaquette-avant.jpg" },
    { nom: "Metroid Dread", genre: ["Action", "Aventure", "Metroidvania"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/163299/1632989749-6428-jaquette-avant.gif" },
    { nom: "Metroid Prime Remastered", genre: ["Fps", "Action", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/167592/1675922859-3644-jaquette-avant.jpg" },
    { nom: "Miraculous Rise Of The Sphinx", genre: ["Action", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/167663/1676626078-3315-jaquette-avant.png" },
    { nom: "New Super Mario Bros. U Deluxe", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo", "Coop Local"], image: "https://image.jeuxvideo.com/medias-sm/154410/1544104487-917-jaquette-avant.jpg" },
    { nom: "Nintendo Switch Sports", genre: ["Sport"], console: ["Switch"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/164450/1644499373-7692-jaquette-avant.jpg" },
    { nom: "Ori And The Blind Forest", genre: ["Plateforme", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/165287/1652867347-4164-jaquette-avant.jpg" },
    { nom: "Ori And The Will Of Wisps", genre: ["Plateforme", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/153061/1530608921-8834-jaquette-avant.jpg" },
    { nom: "Overcooked 1 & 2", genre: ["Simulation", "Gestion"], console: ["Switch"], mode: ["Coop Local", "Coop En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/147014/1470144911-9183-jaquette-avant.jpg" },
    { nom: "Owlboy", genre: ["Plateforme", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/151188/1511883525-2481-jaquette-avant.jpg" },
    { nom: "Paper Mario - La Porte Millenaire", genre: ["Rpg", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/170315/1703151863-8189-jaquette-avant.jpeg" },
    { nom: "Paper Mario The Origami King", genre: ["Rpg", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/159491/1594912273-8454-jaquette-avant.jpg" },
    { nom: "Pikmin 4", genre: ["Stratégie", "Aventure", "Puzzle"], console: ["Switch"], mode: ["Solo", "Coop Local"], image: "https://image.jeuxvideo.com/medias-sm/170291/1702914932-7235-jaquette-avant.jpg" },
    { nom: "Pokemon Epee", genre: ["Rpg", "Aventure"], console: ["Switch"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/157244/1572441416-7551-jaquette-avant.png" },
    { nom: "Pokemon Perle Scintillante", genre: ["Rpg", "Aventure"], console: ["Switch"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/163396/1633959248-729-jaquette-avant.gif" },
    { nom: "Pokemon Violet", genre: ["Rpg", "Aventure"], console: ["Switch"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/166134/1661339183-3131-jaquette-avant.jpg" },
    { nom: "Prince Of Persia - The Lost Crown", genre: ["Action", "Aventure", "Plateforme"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/169814/1698141365-715-jaquette-avant.jpg" },
    { nom: "Princess Peach Showtime", genre: ["Action", "Aventure", "Plateforme"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/170315/1703149442-6851-jaquette-avant.jpg" },
    { nom: "Ravenswatch", genre: ["Rpg", "Action"], console: ["Switch"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/168131/1681313805-8880-jaquette-avant.jpg" },
    { nom: "Rayman Legends", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo", "Coop Local"], image: "https://image.jeuxvideo.com/images-sm/jaquettes/00049641/jaquette-rayman-legends-pc-cover-avant-g-1378220913.jpg" },
    { nom: "Signalis", genre: ["Horreur", "Survival"], console: ["Switch"], mode: ["Solo"], image: "https://m.media-amazon.com/images/I/611sXDCUhDL._AC_UF1000,1000_QL80_.jpg" },
    { nom: "Sine Mora Ex", genre: ["Action"], console: ["Switch"], mode: ["Solo"], image: "https://m.media-amazon.com/images/I/91iUEQ+af1L.jpg" },
    { nom: "Sonic Forces", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo"], image: "https://m.media-amazon.com/images/I/710jZ6GvWJL._AC_UF1000,1000_QL80_.jpg" },
    { nom: "Sonic X Shadow Generation", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/174557/1745568290-6815-jaquette-avant.jpg" },
    { nom: "Splatoon 2", genre: ["Action", "Fps", "Multijoueur"], console: ["Switch"], mode: ["Solo", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/150530/1505295434-194-jaquette-avant.jpg" },
    { nom: "Spirit La Grande Aventure De Lucky", genre: ["Aventure", "Plateforme"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/162607/1626074916-3510-jaquette-avant.jpg" },
    { nom: "Star Renegades", genre: ["Rpg", "Stratégie", "Rogue-Like"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/159618/1596184460-3870-jaquette-avant.jpg" },
    { nom: "Starlink Battle For Atlas", genre: ["Action", "Aventure", ""], console: ["Switch"], mode: ["Solo", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/153633/1536326477-8238-jaquette-avant.jpg" },
    { nom: "Street Fighter Collection", genre: ["Combat"], console: ["Switch"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://m.media-amazon.com/images/I/91h0uudWbeL.jpg" },
    { nom: "Streets Of Rage 4", genre: ["Action"], console: ["Switch"], mode: ["Solo", "Coop Local", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/155368/1553678016-8072-jaquette-avant.jpg" },
    { nom: "Super Mario 3D All Stars", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/159914/1599139135-3122-jaquette-avant.jpg" },
    { nom: "Super Mario 3D World + Bowser'S Fury", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo", "Coop Local"], image: "https://image.jeuxvideo.com/medias-sm/159914/1599139337-1322-jaquette-avant.jpg" },
    { nom: "Super Mario Odyssey", genre: ["Plateforme", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/150166/1501664378-9988-jaquette-avant.jpg" },
    { nom: "Super Mario Party", genre: ["Plateau", "Minijeux"], console: ["Switch"], mode: ["Solo", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/152905/1529049239-2958-jaquette-avant.jpg" },
    { nom: "Super Mario Party Jamboree", genre: ["Plateau", "Minijeux"], console: ["Switch"], mode: ["Solo", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/172019/1720189636-8569-jaquette-avant.jpg" },
    { nom: "Super Mario Rpg", genre: ["Rpg", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/170292/1702916547-13-jaquette-avant.jpg" },
    { nom: "Super Mario Wonder", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo", "Coop Local"], image: "https://image.jeuxvideo.com/medias-sm/170317/1703166833-1293-jaquette-avant.jpg" },
    { nom: "Super Mario Wonder N°2", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo", "Coop Local"], image: "" },
    { nom: "Super Smash Bros Ultimate", genre: ["Combat", "Action"], console: ["Switch"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/152891/1528906153-7510-jaquette-avant.jpg" },
    { nom: "The Legend Of Heroes Trails To Azure", genre: ["Rpg", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/168873/1688730996-5344-jaquette-avant.jpg" },
    { nom: "The Legend Of Zelda : Echoes Of Wisdom", genre: ["Aventure", "Action"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/171873/1718726033-6870-jaquette-avant.jpg" },
    { nom: "The Legend Of Zelda Tears Of The Kingdom ", genre: ["Aventure", "Action"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/166323/1663231496-4522-jaquette-avant.jpg" },
    { nom: "Tortue Ninja : Shredder'S Revenge", genre: ["Action"], console: ["Switch"], mode: ["Solo", "Coop Local"], image: "https://m.media-amazon.com/images/I/71iuSuS96kL.jpg" },
    { nom: "Undertale", genre: ["Rpg", "Aventure"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/144430/1444298844-4196-jaquette-avant.png" },
    { nom: "Wargroove", genre: ["Stratégie", "Tactique"], console: ["Switch"], mode: ["Solo", "Multijoueur Local"], image: "https://image.jeuxvideo.com/medias-sm/155137/1551371912-6930-jaquette-avant.jpg" },
    { nom: "Windjammers 2", genre: ["Sport", "Action"], console: ["Switch"], mode: ["Solo", "Multijoueur Local", "Multijoueur En Ligne"], image: "https://image.jeuxvideo.com/medias-sm/163413/1634126841-4332-jaquette-avant.png" },
    { nom: "Wonder Boy The Dragon'S Trap", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/148960/1489596891-2235-jaquette-avant.jpg" },
    { nom: "Xenoblade Chronicle X", genre: ["Rpg", "Aventure", "Action"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/173022/1730219813-7109-jaquette-avant.jpg" },
    { nom: "Xenoblade Chronicles 3", genre: ["Rpg", "Aventure", "Action"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/164457/1644568129-529-jaquette-avant.png" },
    { nom: "Yoku'S Island Express", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/149494/1494940577-2485-jaquette-avant.jpg" },
    { nom: "Yoshi'S Crafted World", genre: ["Plateforme", "Action"], console: ["Switch"], mode: ["Solo", "Coop Local"], image: "https://image.jeuxvideo.com/medias-sm/154937/1549374361-269-jaquette-avant.jpg" },
    { nom: "The Legend Of Zelda : Breath Of The Wild", genre: ["Aventure", "Action"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/149432/1494322310-8900-jaquette-avant.jpg" },
    { nom: "The Legend Of Zelda : Breath Of The Wild", genre: ["Aventure", "Action"], console: ["Switch"], mode: ["Solo"], image: "" },
    { nom: "The Legend Of Zelda : Link'S Awakening", genre: ["Aventure", "Action", "Plateforme"], console: ["Switch"], mode: ["Solo"], image: "https://image.jeuxvideo.com/medias-sm/158341/1583413282-4503-jaquette-avant.jpg" },
  
    // Switch 2

    // Xbox 360

    // Wii

];