const photographie = [

    { marque: "Nikon", nom: "105 F:2.8 Swm Vr Ed If Micro 1: 1 Phi 62", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Nikon", nom: "Af-S Micro 105Mm F2.8 G Ed", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Nikon", nom: "Af-S 10-24Mm F3.5-4.5 G Ed Dx", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Nikon", nom: "Af-S 18-35Mm F3.5-4.5 G", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Nikon", nom: "Af-S 17-55Mm F2.8 G Ed Dx", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Nikon", nom: "Af-S 28-105Mm F3.5-4.5 D", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Nikon", nom: "Af 70-300Mm F4-5.6 D Ed Vr", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Nikon", nom: "Af-S 200-500Mm F5.6 E Ed Vr", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Nikon", nom: "Speedlight Sb 600", materiel: "Accessoire", accessoire: "Flash externe", photo: "", video: "" },
    { marque: "Nikon", nom: "Speedlight Sb 800", materiel: "Accessoire", accessoire: "Flash externe", photo: "", video: "" },
    { marque: "Nikon", nom: "Speedlight Sb 700 N°1", materiel: "Accessoire", accessoire: "Flash externe", photo: "", video: "" },
    { marque: "Nikon", nom: "D600 (24Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Nikon", nom: "Speedlight Sb 700 N°2", materiel: "Accessoire", accessoire: "Flash externe", photo: "", video: "" },
    { marque: "Nikon", nom: "Af-S 28-300Mm F3.5-5.6 G Ed Vr", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Nikon", nom: "Af-S 18-105Mm F3.5-5.6 G Ed Dx Vr", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Canon", nom: "Eos 5D Mark Ii (21Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Canon", nom: "600D (18Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Canon", nom: "1200D (18Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Canon", nom: "Ef 35Mm F2 Is Usm", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Canon", nom: "Ef 50Mm F1.8 Ii", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Canon", nom: "Ef 85Mm F1.8", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Canon", nom: "Ef 100Mm F2.8 L Macro Is Usm", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Nikon", nom: "D7200 (24Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Canon", nom: "Ef-S 10-22Mm F3.5-4.5 Usm", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Canon", nom: "Ef 17-40Mm F4 L Usm", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Canon", nom: "Ef 70-200Mm F4 L Is Usm", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Canon", nom: "G9X 28-84 Mm F/2-4,9 (20,2Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Canon", nom: "G5X 24-100 Mm F/1. 8-2.8 (20,2Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Canon", nom: "S120 24-120Mm F/1,8-5,7 (12,1Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Canon", nom: "G9 35-210Mm F/2-4 (12,1Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Canon", nom: "G9X Mkii 28-84 Mm F/2-4,9 (20,2Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Canon", nom: "Speedlite 420 Ex", materiel: "Accessoire", accessoire: "Flash externe", photo: "", video: "" },
    { marque: "Canon", nom: "Speedlite 580 Ex", materiel: "Accessoire", accessoire: "Flash externe", photo: "", video: "" },
    { marque: "Nikon", nom: "D7100 (24Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Olympus", nom: "Om-D E-M5 Ii", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Olympus", nom: "12-40 Mm 1:2,8", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Olympus", nom: "Stylus Tough Tg-5 25-100Mm F/2.0-4.9  (12.0 Mp) Noir", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Olympus", nom: "Stylus Tough Tg-4 25-100Mm F/2.0-4.9 (16.0 Mp) Rouge", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Nikon", nom: "105Mm F2.8 Macro", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "", nom: "70-300Mm", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "", nom: "12 Mm, 20 Mm, 36 Mm", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "", nom: "12 Mm, 20 Mm, 36 Mm", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Fujifilm", nom: "X20 28-112Mm F/2-2,8 (12Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Panasonic/Lumix", nom: "Fz200 25 - 600Mm F/2.8 (12.1Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Nikon", nom: "D5100 (16.2Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Manfrotto", nom: "Chasseur D'Image", materiel: "Accessoire", accessoire: "Trépied", photo: "", video: "" },
    { marque: "Gitzo", nom: "Trépied", materiel: "Accessoire", accessoire: "", photo: "", video: "" },
    { marque: "", nom: "Spirit 161", materiel: "Accessoire", accessoire: "Trépied", photo: "", video: "" },
    { marque: "Bilora", nom: "Trépied", materiel: "Accessoire", accessoire: "", photo: "", video: "" },
    { marque: "", nom: "Petit Trépied Ft-362A", materiel: "Accessoire", accessoire: "Trépied", photo: "", video: "" },
    { marque: "", nom: "Mini-Trépied", materiel: "Accessoire", accessoire: "Trépied", photo: "", video: "" },
    { marque: "Benro", nom: "Monopode Carbone C18T", materiel: "Accessoire", accessoire: "", photo: "", video: "" },
    { marque: "", nom: "Ideal", materiel: "Accessoire", accessoire: "Trépied", photo: "", video: "" },
    { marque: "Optoma", nom: "Optoma Hd71", materiel: "Appareil", accessoire: "Vidéoprojecteur", photo: "non", video: "oui" },
    { marque: "", nom: "Kit Flash Studio", materiel: "Accessoire", accessoire: "Flash", photo: "", video: "" },
    { marque: "Nikon", nom: "Af-S 35Mm F1.8 G Dx", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "", nom: "4990", materiel: "Scanner", accessoire: "", photo: "", video: "" },
    { marque: "Lowepro", nom: "Spider 4 Elite", materiel: "Accessoire", accessoire: "Harnais", photo: "", video: "" },
    { marque: "Lowepro", nom: "Flipside 500 Aw", materiel: "Accessoire", accessoire: "Sac photo", photo: "", video: "" },
    { marque: "", nom: "Print Fx Pro", materiel: "Accessoire", accessoire: "Impression", photo: "", video: "" },
    { marque: "", nom: "Kit De Nettoyage Capteur", materiel: "Accessoire", accessoire: "Nettoyage", photo: "", video: "" },
    { marque: "", nom: "Récepteur + 3 Cables", materiel: "Accessoire", accessoire: "", photo: "", video: "" },
    { marque: "", nom: "Récepteur + 3 Cables", materiel: "Accessoire", accessoire: "", photo: "", video: "" },
    { marque: "", nom: "Télécommande", materiel: "Accessoire", accessoire: "", photo: "", video: "" },
    { marque: "Chapak", nom: "Sac À Dos", materiel: "Accessoire", accessoire: "", photo: "", video: "" },
    { marque: "Spyder", nom: "Mire De Calibration", materiel: "Accessoire", accessoire: "", photo: "", video: "" },
    { marque: "Nikon", nom: "Af-S 50Mm F1.8 G", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "", nom: "R-Strap", materiel: "Accessoire", accessoire: "Sangle", photo: "", video: "" },
    { marque: "Nikon", nom: "Z6 (24Mp)", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Nikon", nom: "Af-S 85Mm F1.8 G", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Nikon", nom: "Af-D 85Mm F1.8 D", materiel: "Objectif", accessoire: "Objectif", photo: "", video: "" },
    { marque: "Gopro", nom: "Hero 11", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },
    { marque: "Gopro", nom: "Hero 13", materiel: "Appareil", accessoire: "", photo: "oui", video: "oui" },



]